### PR TITLE
Derive common traits for `Pid`; update to 2018 edition

### PR DESCRIPTION
**Pull request by hannobraun**

### CODE REVIEW

**Comment by braincore** [comment]
Thanks for the PR and sorry for the delay! I haven't been using rust recently, and hadn't ever added serde as an optional feature. Can you please update the README to include this functionality?

**Comment by hannobraun** [comment]
Done!

**Comment by braincore** [comment]
Thanks! Published as v2.1.0. Let me know if you want any more credit than the git history.

If you don't mind, how are you using this crate?

**Comment by hannobraun** [comment]
Thanks for merging and publishing, and thanks for the library, of course! Credit in Git history is fine, thanks for offering.

> If you don't mind, how are you using this crate?

I'm working on a multiplayer game (as a hobby) involving spaceships, and I'm using the PID controller for missile guidance (well, right now it's just a "P" controller; need to do some tuning :-) ).

I plan to publish the repository some time within the next few weeks. Do you want me to ping you once that happens?

**Comment by braincore** [comment]
Sure!

**Comment by hannobraun** [comment]
Took me a bit longer than expected, but it's out: https://github.com/hannobraun/vndf

Never quite got around to tuning the [PID controller](https://github.com/hannobraun/vndf/blob/8d7709c763cb5993e491910f51fbc2acce2e9d82/vndf-shared/src/game/missiles/components.rs#L80), unfortunately.

**Pull request merged**
